services:
    db:
        image: postgres:15-alpine
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - golden_net
        healthcheck:
            test: CMD wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1
            interval: 30s
            timeout: 10s
            start_period: 5s
            retries: 3

volumes:
    postgres_data:

networks:
    golden_net:
        name: golden_net
